language: python
python:
  - "2.7"
  - "3.4"  # When support for 3.4 is removed unpin the PyYAML version below.
  - "3.6"
# command to install dependencies
install:
  - pip install PyYAML==5.2 # Forcing PyYAML 5.2 while we retain Python 3.4 support PyYAML 5.3 and higher does not support python 3.4
  - pip install argparse rosdep vcstools catkin-pkg python-dateutil setuptools
  - pip install nose coverage pep8
  - git clone https://github.com/dirk-thomas/empy.git /tmp/empy
  - cd /tmp/empy
  - python setup.py install
  - cd -
  - sudo `which rosdep` init
  - rosdep update
# command to run tests
script:
  - BLOOM_VERBOSE=1 python setup.py nosetests -s --tests test
notifications:
  email: false
